
# This is a basic workflow to help you get started with the Run Jtest action.
name: JtestOnLinuxUT

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    name: Analyze project with Jtest using Gradle
    
    permissions:
      # required for all workflows
      security-events: write
      
    # Specifies the type of runner that the job will run on.
    runs-on: [self-hosted, Linux]

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Generates the jtest.data.json input file.
    - name: Create input for Jtest
      run: ./gradlew jtest-agent test jtest -I /home/parasoft/apps/jtest-under-test/integration/gradle/init.gradle -Djtest.config="builtin://Unit Tests"

    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Static analysis reports
        path: build/jtest/*.*